apiVersion: v1
kind: List
items:

 # Setup the permission required to read the config map
 - apiVersion: v1
   kind: RoleBinding
   metadata:
     name: some-role
   subjects:
    - kind: ServiceAccount
      name: default
   roleRef:
      name: view
      
 # The content of the config map - must be kept in sync with the app-config.yml
 # Name must also match
 - apiVersion: v1
   kind: ConfigMap
   metadata:
     name: app-config
   data:
     app-config.yml: |-
       message : "Hello, %s from a ConfigMap !"
       level : INFO
